services:
  AdGuard:
    image: adguard/adguardhome
    container_name: AdGuard
    network_mode: "host"
    restart: "always"
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
      - "68:68/udp"
      - "80:80/tcp"
      - "443:443/tcp"
      - "443:443/udp"
      - "3000:3000/tcp"
      - "853:853/tcp"
      - "853:853/udp"
      - "784:784/udp"
      - "8853:8853/udp"
      - "5443:5443/tcp"
      - "5443:5443/udp"
  
  Portainer:
    image: portainer/portainer-ce:latest
    container_name: Portainer
    network_mode: "host"
    restart: "always"
    ports:
      - "8000:8000"
      - "9443:9443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
  
  GitPod:
    image: gitpod/openvscode-server
    container_name: GitPod
    restart: "always"
    ports:
      - "3004:3000"
    volumes:
      - $HOME:/home/workspace:cached

  Jellyfin:
    image: jellyfin/jellyfin
    container_name: Jellyfin
    user: 1000:1000
    network_mode: "host"
    volumes:
      - $HOME/jellyfin/jellyfin-config:/config
      - $HOME/jellyfin/jellyfin-cache:/cache
      - $HOME/jellyfin/jellyfin-medias/media:/media
      - $HOME/jellyfin/jellyfin-medias/media2:/media2:ro
    restart: "always"

  Nextcloud:
    image: nextcloud
    container_name: NextCloud
    ports:
      - "3333:80"
    volumes:
      - nextcloud:/var/www/html
      - nextcloud_data:/var/www/html/data
      - nextcloud_config:/var/www/html/config
      - $HOME/jellyfin/jellyfin-medias/media:/external/
    restart: "always"

volumes:
  portainer_data:
    external: false
  nextcloud:
    external: false
  nextcloud_data:
    external: false
  nextcloud_config:
    external: false
