services:
  AdGuard:
    image: adguard/adguardhome
    container_name: AdGuard
    network_mode: "host"
    restart: "always"
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
      - "68:68/udp"
      - "80:80/tcp"
      - "443:443/tcp"
      - "443:443/udp"
      - "3000:3000/tcp"
      - "853:853/tcp"
      - "853:853/udp"
      - "784:784/udp"
      - "8853:8853/udp"
      - "5443:5443/tcp"
      - "5443:5443/udp"
  
  Portainer:
    image: portainer/portainer-ce:latest
    container_name: Portainer
    network_mode: "host"
    restart: "always"
    ports:
      - "8000:8000"
      - "9443:9443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data

  Theia:
    image: ghcr.io/eclipse-theia/theia-blueprint/theia-ide:latest
    ports: 
      - "3004:3000"
    volumes:
      - $HOME/projects/:/projects

volumes:
  portainer_data:
    external: false
